name: Deploy MyGhost Theme
on:
  release:
    types: [published, released]
jobs:
  deploy:
    name: Deploy MyGhost theme to nguyenhongthe.net
    runs-on: ubuntu-latest
    if: github.event_name == 'release' && github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4.1.7
      - name: Deploy Ghost Theme
        uses: TryGhost/action-deploy-theme@v1.6.6
        with:
          api-url: ${{ secrets.GHOST_ADMIN_API_URL }}
          api-key: ${{ secrets.GHOST_ADMIN_API_KEY }}
