name: Deploy MyGhost Theme
on:
  pull_request:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/to_ghost_blog.yml'
jobs:
  deploy:
    name: Deploy MyGhost theme to nguyenhongthe.net
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3
      - name: Deploy Ghost Theme
        uses: TryGhost/action-deploy-theme@v1.6.4
        with:
          api-url: ${{ secrets.GHOST_ADMIN_API_URL }}
          api-key: ${{ secrets.GHOST_ADMIN_API_KEY }}
